#! /bin/csh -f

set port = 9999
if ( "$1" != "" ) set port="$1"

nohup
nice

if ( -e shutdown.txt ) rm -f shutdown.txt

while ( 1 )
    ./swr $port

    if ( -e shutdown.txt ) then
	rm -f shutdown.txt
	exit 0
    endif
    sleep 15
end
